language: python

python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

before_install:
 - export MINICONDA=$HOME/miniconda
 - export PATH="$MINICONDA/bin:$PATH"
 - hash -r
 # Install gfortran (for instaseis)
 - sudo apt-get update
 # Install conda only if necessary
 - command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -f -p $MINICONDA; }
 - conda update --yes conda
 - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
 - conda install --yes -n condaenv pip
 - source activate condaenv
 # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
 # These are mostly requirements of instaseis
 - conda install --yes -c obspy nomkl obspy pytest python=$TRAVIS_PYTHON_VERSION
 - travis_retry pip install $PIP_DEPS
 - pip install basemap

install:
 - pip install .
# command to run tests
script: py.test
